version: "3.5"

services:

  library-api:
    build: .
    image: library-api
    container_name: library-api
    ports:
      - 80:3000
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      - "COUNTER_PORT=3000"
      - "MONGO_HOST=mongodb"
      - "MONGO_PORT=27017"
      - "MONGO_DB=library"
      - "MONGO_USER=${DB_USERNAME:-root}"
      - "MONGO_PASSWORD=${DB_PASSWORD:-password}"

  mongodb:
    image: mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}"
      - "MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}"
      - "MONGO_INITDB_DATABASE=library"

